### ISSUE TITLE
Option to hide title in HTML view

### ISSUE THREAD

**Issue by rugk** [ether/ep_set_title_on_pad#11]
It would be nice if you could hide the title, so it is only shown in the browser title.

**Comment by JohnMcLear** [comment]
How would you edit it?  Only in drop down?

**Comment by rugk** [comment]
By activating the option to show it again... :smiley:

**Comment by JohnMcLear** [comment]
Mheh, If someone wants to sponsor then sure but tbh I'm not interested in this.

**Comment by JohnMcLear** [comment]
Done 👍

**Comment by rugk** [comment]
Awesome! Thanks.
