### ISSUE TITLE
Append "title" to tab title

### ISSUE THREAD

**Issue by rugk** [ether/ep_set_title_on_pad#12]
The "title" set in the settings (default: "Etherpad") should still be appended to the tab title.

**Comment by JohnMcLear** [comment]
I'm not sure I understand what you mean ;\  Can you elaborate?

**Comment by rugk** [comment]
Yes, I guess this is what I've meant ~4 years ago… :thinking: 

Append the title of the pad to the browser tab title.

**Comment by JohnMcLear** [comment]
You can just accomplish this by doing Etherpad: Whatevrz...  I don't wanna break the UX here.
