### ISSUE TITLE
Set the default title to PadName

### ISSUE THREAD

**Issue by voidspacexyz** [ether/ep_set_title_on_pad#16]
Instead of setting Untitled Page as the default name, we should set the Pad name as the default name. Basically, https://padsiteurl/p/testing would mean, testing is the default title.

**Comment by JohnMcLear** [comment]
It would be important to sanitize the input IE ``<script>alert("hello world");</script>`` should be escaped before inserting into the input and view.

**Comment by JohnMcLear** [comment]
Done
