### ISSUE TITLE
Please add a locales folder

### ISSUE THREAD

**Issue by ovari** [ether/ep_set_title_on_pad#22]
Please allow the following to be translated:

`Untitled Pad`
https://github.com/JohnMcLear/ep_set_title_on_pad/blob/master/templates/title.ejs#L2

`OK`
https://github.com/JohnMcLear/ep_set_title_on_pad/blob/master/templates/title.ejs#L5

Thank you

**Comment by JohnMcLear** [comment]
just a quick heads up I'm not going to get tied to add these values so the best thing you can do is just to do it yourself if you look at how other plugins I've done it for example page for you then you'll be able to say that it's just a case of adding a string de ejs file

**Comment by JohnMcLear** [comment]
Done

**Comment by ovari** [comment]
Don't know why but there are failing tests at https://github.com/ether/ep_set_title_on_pad/pull/24
